version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    configs:
      - source: buscaprecos_db_seed
        target: /seed/backup.sql
        uid: "0"
        gid: "0"
        mode: 0444
    networks:
      - network_internal
    deploy:
      replicas: 1
      restart_policy: { condition: on-failure }

volumes:
  db_data:

configs:
  buscaprecos_db_seed:
    external: true

networks:
  network_internal:
    external: true
    name: network_internal