version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=buscaprecos
      - DB_USER=busca
      - DB_PASSWORD=busca_password

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: buscaprecos
      MYSQL_USER: busca
      MYSQL_PASSWORD: busca_password
      MYSQL_ROOT_PASSWORD: root_password_123

  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"

volumes:
  db_data: