# docker-compose.yml (VERSÃO CORRIGIDA PARA PRODUÇÃO COM TRAEFIK)
services:
  # Serviço PHP
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    networks:
      - default
      - web

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default
      - web

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true" # Habilita o Traefik para este contêiner
      - "traefik.http.routers.algorise.rule=Host(`app.algorise.com.br`)" # Domínio Algorise
      - "traefik.http.routers.algorise.entrypoints=websecure" # Usa a entrada segura (HTTPS)
      - "traefik.http.routers.algorise.tls.certresolver=letsencrypt" # Pede um certificado SSL
      - "traefik.http.services.algorise.loadbalancer.server.port=80" # Redireciona para a porta 80 interna do Nginx

# Seção para definir o volume do banco de dados
volumes:
  db_data:

# Seção para definir as redes que os serviços usam
networks:
  default: # A rede interna padrão da stack
  web:
    external: true # Informa que a rede 'web' já existe e foi criada manualmente por nós