# docker-compose.yml (VERSÃO CORRIGIDA PARA PRODUÇÃO)
services:
  # Serviço PHP
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

# Seção para definir o volume do banco de dados
volumes:
  db_data: