version: "3.9"
services:
  webserver:
    image: pbraconnot/buscaprecos-web:1.0.0
    networks:
      - network_internal
      - network_public
    deploy:
      replicas: 1
      restart_policy: { condition: on-failure }
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public

        # HTTPS router (Let’s Encrypt)
        - traefik.http.routers.buscaprecos.rule=Host(`${APP_HOST}`)
        - traefik.http.routers.buscaprecos.entrypoints=websecure
        - traefik.http.routers.buscaprecos.tls=true
        - traefik.http.routers.buscaprecos.tls.certresolver=letsencryptresolver
        - traefik.http.services.buscaprecos.loadbalancer.server.port=80

        # HTTP router to allow ACME http-01 and redirect to HTTPS
        - traefik.http.routers.buscaprecos-http.rule=Host(`${APP_HOST}`)
        - traefik.http.routers.buscaprecos-http.entrypoints=web
        - traefik.http.routers.buscaprecos-http.priority=1
        - traefik.http.routers.buscaprecos-http.middlewares=redirect-to-https

        # Local redirect middleware (defined on same service)
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

networks:
  network_public:
    external: true
    name: network_public
  network_internal:
    external: true
    name: network_internal